package com.softeer.backend.global.staticresources.constant;

/**
 * DB에 저장된 S3 url의 파일 이름을 관리하는 enum 클래스
 */
public enum S3FileName {
    CHARGING_BACKGROUND_IMAGE,
    CHARGING_FAST_IMAGE,
    CHARGING_THUMBNAIL_IMAGE,
    CHARGING_V2L_IMAGE,
    DRAW_REWARD_IMAGE_1,
    DRAW_REWARD_IMAGE_2,
    DRAW_REWARD_IMAGE_3,
    FCFS_REWARD_IMAGE_1,
    FCFS_REWARD_IMAGE_2,
    INTERIOR_BACKGROUND_IMAGE,
    INTERIOR_OPENNESS_IMAGE,
    INTERIOR_THUMBNAIL_IMAGE,
    INTERIOR_WELLNESS_IMAGE,
    IONIQ_VIDEO,
    MAIN_BACKGROUND_IMAGE,
    MAIN_THUMBNAIL_IMAGE,
    PERFORMANCE_BACKGROUND_IMAGE,
    PERFORMANCE_BRAKING_IMAGE,
    PERFORMANCE_DRIVING_IMAGE,
    PERFORMANCE_THUMBNAIL_IMAGE,
    SAFE_ADVANCED_IMAGE,
    SAFE_BACKGROUND_IMAGE,
    SAFE_DRIVING_IMAGE,
    SAFE_THUMBNAIL_IMAGE,
    BARCODE_IMAGE,
    SEVENTH_COMPLETE_IMAGE,
    SEVENTH_NOT_YET_IMAGE,
    ATTENDANCE_REWARD_IMAGE,
    DRAW_BLOCK_DOWN_IMAGE,
    DRAW_BLOCK_LEFT_IMAGE,
    DRAW_BLOCK_RIGHT_IMAGE,
    DRAW_BLOCK_UP_IMAGE,
    DRAW_REWARD_IMAGE_2_3
}
