package com.softeer.backend.global.staticresources.constant;

import lombok.Getter;

/**
 * DB에 저장된 정적 텍스트 데이터의 이름을 관리하는 enum 클래스
 */
public enum StaticTextName {
    EVENT_TITLE,
    EVENT_DESCRIPTION,

    FCFS_INFO,
    FCFS_TITLE,
    FCFS_CONTENT,

    TOTAL_DRAW_WINNER,
    REMAIN_DRAW_COUNT,
    DRAW_TITLE,
    DRAW_CONTENT,
    DRAW_REWARD_NAME_1,
    DRAW_REWARD_NAME_2,
    DRAW_REWARD_NAME_3,
    FCFS_REWARD_NAME_1,
    FCFS_REWARD_NAME_2,

    MAIN_TITLE,
    MAIN_SUBTITLE,

    INTERIOR_TITLE,
    INTERIOR_SUBTITLE,
    INTERIOR_IMAGE_TITLE,
    INTERIOR_IMAGE_CONTENT,
    INTERIOR_OPENNESS_TITLE,
    INTERIOR_OPENNESS_SUBTITLE,
    INTERIOR_OPENNESS_CONTENT,

    INTERIOR_WELLNESS_TITLE,
    INTERIOR_WELLNESS_SUBTITLE,
    INTERIOR_WELLNESS_CONTENT,

    PERFORMANCE_TITLE,
    PERFORMANCE_SUBTITLE,
    PERFORMANCE_IMAGE_TITLE,
    PERFORMANCE_IMAGE_CONTENT,
    PERFORMANCE_BRAKING_TITLE,
    PERFORMANCE_BRAKING_SUBTITLE,
    PERFORMANCE_BRAKING_CONTENT,

    PERFORMANCE_DRIVING_TITLE,
    PERFORMANCE_DRIVING_SUBTITLE,
    PERFORMANCE_DRIVING_CONTENT,

    CHARGING_TITLE,
    CHARGING_SUBTITLE,
    CHARGING_IMAGE_TITLE,
    CHARGING_IMAGE_CONTENT,
    CHARGING_FAST_TITLE,
    CHARGING_FAST_SUBTITLE,
    CHARGING_FAST_CONTENT,

    CHARGING_V2L_TITLE,
    CHARGING_V2L_SUBTITLE,
    CHARGING_V2L_CONTENT,

    SAFE_TITLE,
    SAFE_SUBTITLE,
    SAFE_IMAGE_TITLE,
    SAFE_IMAGE_CONTENT,
    SAFE_DRIVING_TITLE,
    SAFE_DRIVING_SUBTITLE,
    SAFE_DRIVING_CONTENT,

    SAFE_ADVANCED_TITLE,
    SAFE_ADVANCED_SUBTITLE,
    SAFE_ADVANCED_CONTENT,

    // 7일 연속 출석 모달
    FULL_ATTEND_MODAL_TITLE,
    FULL_ATTEND_MODAL_SUBTITLE,
    FULL_ATTEND_MODAL_DESCRIPTION,

    // 추첨 당첨 모달
    DRAW_WINNER_MODAL_TITLE,
    DRAW_FIRST_WINNER_SUBTITLE,
    DRAW_SECOND_WINNER_SUBTITLE,
    DRAW_THIRD_WINNER_SUBTITLE,
    DRAW_WINNER_MODAL_DESCRIPTION,

    // 공유 url
    BASE_URL,
    NON_USER_SHARE_URL,

    // 선착순
    FCFS_QUIZ_DESCRIPTION,

    FCFS_WINNER_TITLE,
    FCFS_WINNER_SUBTITLE,
    FCFS_WINNER_CODE_WORD,
    FCFS_WINNER_EXPIRY_DATE,
    FCFS_WINNER_CAUTION,

    FCFS_LOSER_TITLE,
    FCFS_LOSER_SUBTITLE,
    FCFS_LOSER_CAUTION,

    // 선착순 이벤트 종료로 인한 응모 실패 모달
    FCFS_CLOSED_TITLE,
    FCFS_CLOSED_SUBTITLE,

    // 선착순 이벤트 당첨된 상황에서 중복으로 응모할 때의 실패 모달
    FCFS_DUPLICATED_TITLE,
    FCFS_DUPLICATED_SUBTITLE;

}
